### ISSUE TITLE
Use _msgSender() and _msgData() so that meta-transactions will work correctly

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/support#100]
I created the issue https://github.com/axelarnetwork/interchain-token-service/issues/229 4 months ago but it was closed, so I'm bringing it up again as it should still very much be done.

We all need to make the onboarding experience of new users to crypto platforms much smoother. Eliminating the need for people who are new to crypto (and don't have accounts at any exchanges) to go find some native blockchain currency in order to use a platform for the first time would be a huge improvement, leading to increased adoption.

**Comment by SKYBITDev3** [comment]
Please work on it.

**Comment by benjamin852** [comment]
Hey @SKYBITDev3 appreciate you bumping this. The team is very tied up with many other tasks right now, I cannot commit here on behalf of this team that it will be done in the immediate future. 
cc @milapsheth for visibility of this feature request for future reference.
