### ISSUE TITLE
its always show as pending

### ISSUE THREAD

**Issue by itsMeNoName** [axelarnetwork/support#107]
![image](https://github.com/axelarnetwork/support/assets/59513917/bede96ad-723a-4db3-87c9-a49e9ff36b49)

**Comment by Olanetsoft** [comment]
Hey @itsMeNoName, can you please tell us what browser you are using and the version and chain you are on before trying to deploy remotely? is this testnet or mainnnet?

**Comment by itsMeNoName** [comment]
are you still with me?

**Comment by Olanetsoft** [comment]
Yes, please, @itsMeNoName. I am with you. I understand your request for you to use the lock and unlock token feature for ITS, but that means you might have to do it programmatically yourself as you can't use the portal to do that today; this is a feature yet to go live on the ITS portal but available on ITS contract to be done programmatically.

To programmatically configure this option, you will need to deploy a lock and unlock token manager type as indicated [here](https://github.com/axelarnetwork/interchain-token-service/blob/cd8f7be582eaa86a7de9a098fcfc5121e3a39af1/contracts/interfaces/ITokenManagerType.sol#L13). You can follow this [step by step guide to programmatically](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens) do this. Something to note in the guide is that the Mint/Burn type token manager was used, but all you need to do is to change the enum to use the lock/unlock type.

 Let me know if that helps or if you have any other questions. Thanks

**Comment by Olanetsoft** [comment]
Closing this, now stale.
