### ISSUE TITLE
Call Interchain Token Protocol problem

### ISSUE THREAD

**Issue by flashbobi** [axelarnetwork/support#108]
Hi, sir i wanna call Interchain Token Protocol  (0xB5FB4BE02232B1bBA4dC8f81dc24C26980dE9e3C)  to transfer RBX(0x3Ba925fdeAe6B46d0BB4d424D829982Cb2F7309e)  token from Eth to Blast in etherscan ,but  after i fill in all the parameters, i press write button ,it doesnt work for metamask to pop up .. can you help to check which mistake i made?  Will be really appreciated for  your help

**Comment by flashbobi** [comment]
![04131552](https://github.com/axelarnetwork/support/assets/86477418/675e0a64-996a-4ffb-938b-7d39e9caebd8)

**Comment by benjamin852** [comment]
Hey the metadata should not just be the string `bytes` if you want it to be empty it should be `0x`
