### ISSUE TITLE
ITS Portal down

### ISSUE THREAD

**Issue by ekkis** [axelarnetwork/support#109]
I want to create a test token using https://testnet.interchain.axelar.dev/ but when I visit I see a message thaty reads "loading page data" and I never get the page.  if I look in the console I see:
```
_app-48fe23bc22a1f2a5.js:18 
        
        
       GET https://testnet.interchain.axelar.dev/api/trpc/axelarscan.getEVMChainConfigs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 500 (Internal Server Error)
(anonymous) @ _app-48fe23bc22a1f2a5.js:18
q @ _app-48fe23bc22a1f2a5.js:26
await in q (async)
V.promise @ _app-48fe23bc22a1f2a5.js:26
V @ _app-48fe23bc22a1f2a5.js:26
W @ _app-48fe23bc22a1f2a5.js:26
(anonymous) @ _app-48fe23bc22a1f2a5.js:26
i @ _app-48fe23bc22a1f2a5.js:26
s @ _app-48fe23bc22a1f2a5.js:1
setTimeout (async)
(anonymous) @ _app-48fe23bc22a1f2a5.js:1
load @ _app-48fe23bc22a1f2a5.js:26
(anonymous) @ _app-48fe23bc22a1f2a5.js:26
subscribe @ _app-48fe23bc22a1f2a5.js:23
(anonymous) @ _app-48fe23bc22a1f2a5.js:26
subscribe @ _app-48fe23bc22a1f2a5.js:23
(anonymous) @ _app-48fe23bc22a1f2a5.js:26
subscribe @ _app-48fe23bc22a1f2a5.js:23
promise @ _app-48fe23bc22a1f2a5.js:26
requestAsPromise @ _app-48fe23bc22a1f2a5.js:26
query @ _app-48fe23bc22a1f2a5.js:26
g.queryFn @ _app-48fe23bc22a1f2a5.js:26
fetchFn @ _app-48fe23bc22a1f2a5.js:103
v @ _app-48fe23bc22a1f2a5.js:103
(anonymous) @ _app-48fe23bc22a1f2a5.js:103
Promise.then (async)
(anonymous) @ _app-48fe23bc22a1f2a5.js:103
Promise.catch (async)
v @ _app-48fe23bc22a1f2a5.js:103
u @ _app-48fe23bc22a1f2a5.js:103
fetch @ _app-48fe23bc22a1f2a5.js:103
#q @ _app-48fe23bc22a1f2a5.js:103
onSubscribe @ _app-48fe23bc22a1f2a5.js:103
subscribe @ _app-48fe23bc22a1f2a5.js:103
(anonymous) @ _app-48fe23bc22a1f2a5.js:103
lN @ framework-63c261f7457c35c5.js:25
oB @ framework-63c261f7457c35c5.js:25
uU @ framework-63c261f7457c35c5.js:25
u @ framework-63c261f7457c35c5.js:25
x @ framework-63c261f7457c35c5.js:49
R @ framework-63c261f7457c35c5.js:49
_app-48fe23bc22a1f2a5.js:18 
        
        
       GET https://testnet.interchain.axelar.dev/api/trpc/axelarscan.getEVMChainConfigs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 500 (Internal Server Error)
```
this happens when I connect to the Fantom testnet and I haven't yet tried other chains

**Comment by ekkis** [comment]
I also noticed that when I click on the account, it allows me to select My Interchain Tokens (the main page doesn't allow that).  I was then able to specify the parameters for the creatino of a token but when I actually try it I get the following:
```

```
{
  "message": "Cannot read properties of undefined (reading 'toLowerCase')",
  "stack": [
    "TypeError: Cannot read properties of undefined (reading 'toLowerCase')",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/61-748b278e5b748bd8.js:1:7644",
    "    at Array.find (<anonymous>)",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/61-748b278e5b748bd8.js:1:7602",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-48fe23bc22a1f2a5.js:96:1658",
    "    at D (https://testnet.interchain.axelar.dev/_next/static/chunks/107.875929d91777e239.js:1:7091)",
    "    at lk (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:60903)",
    "    at i (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:119420)",
    "    at uD (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:99073)",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98940",
    "    at uI (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98947)",
    "    at uE (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:95699)",
    "    at uT (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:96088)",
    "    at r6 (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:44813)",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:93599"
  ],
  "cause": {
    "name": "React ErrorBoundary TypeError"
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "url": "https://testnet.interchain.axelar.dev/interchain-tokens",
  "locale": "en-US",
  "isRTL": false
}
```

**Comment by benjamin852** [comment]
Hey thanks for sharing, can you confirm if this is still happening for you? Site is live for me, thanks!

**Comment by ekkis** [comment]
yes, I'm still getting the 500s and the page doesn't finish loading

**Comment by ekkis** [comment]
if I call one of the failed urls myself I get something like this (clearly broken):
```
[{"error":{"json":{"message":"Failed to get chain config","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"axelarscan.getEVMChainConfigs","zodError":null}}}}]
```

**Comment by ekkis** [comment]
it's still broken from what I can see.  happy to jump on a call

**Comment by benjamin852** [comment]
Hey yes feel free to reach out over email and we can schedule something. ben@interoplabs.io

**Comment by benjamin852** [comment]
Closing this issue now as I have not heard of anyone else having this issue. @ekkis if you're still having this issue happy to schedule a call to see what's going on in your case. Leaving my calendly [here](https://calendly.com/ben-axelar/30min)
