### ISSUE TITLE
Should allow interchain transfer only between specific chains

### ISSUE THREAD

**Issue by ruymaster** [axelarnetwork/support#110]
Bridge should allow tranafer for only specific chain
- should make whitelist for supported chains for a cross token, and allow only transfer for whitelisted chains

**Comment by benjamin852** [comment]
Hey, is there an issue you're having implementing this?

**Comment by ruymaster** [comment]
I mean that axelar need to support it.

**Comment by benjamin852** [comment]
This could be built into your contract i.e. you have a `require` statement that only a specific bridge name can be passed into the `destinationChain` in your `callContract` function
