### ISSUE TITLE
GMP example for EVM <> EVM-equivalent chain, based on Cosmos SDK ( e.g Haqq Network )

### ISSUE THREAD

**Issue by yasiriqbal776** [axelarnetwork/support#119]
I am trying to send GMP from Polygon to Haqq network. I can see examples from EVM to cosmos based chain Haqq network.  But i am unable to understand how on Haqq chain Solidity contract will receive message.  I did deployed contract on polygon and send message to haqq chain. https://axelarscan.io/gmp/0x1a012682aab6235ed85824f5158fed9685fe9b8d2e4a53cf182c65bd66916ce2.  But i am not able to receive message.  Any Help would be appreciated. Thank you.

**Comment by Olanetsoft** [comment]
@yasiriqbal776 I can see this is now executed. Can you share the contract code you used to initiate this call?

**Comment by asimashfaq** [comment]
This is our contract address on Haqq
https://explorer.haqq.network/address/0xA76Fc0bF6fFBa17fab8dDB3b62f49eE3a9750c59?tab=txs.
as you can see it have no transaction.
Nor this returning any details https://ping.pub/haqq/account/haqq1wttkx8xa3t5s8ups3vmgzjecurzv4fvfq7hrm9.

But if we see this https://axelarscan.io/gmp/0x1a012682aab6235ed85824f5158fed9685fe9b8d2e4a53cf182c65bd66916ce2
it shows its executed successfully and run the transaction.
