### ISSUE TITLE
Wrap Cosmos-based blockchain

### ISSUE THREAD

**Issue by golnar-m** [axelarnetwork/support#120]
Hello,

I need to wrap our cosmos-based native token. I need your help to understand the steps. What is the first step?

We need to wrap our Cosmos-based native token for use in EVM chains. What are the steps for doing this? I found an example on Ethereum here: [Etherscan Link](https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2#writeContract). How can we create this for our Cosmos token?

1- Where should I start?
2- If a Solidity smart contract is needed, could you please share a relevant document link? I couldn't find anything specific to wrapping Cosmos tokens.

Please list me the steps.

Thank you

**Comment by golnar-m** [comment]
Any idea Axelar support?

**Comment by benjamin852** [comment]
Hi @golnar-m just to confirm your chain still needs to be connected to Axelar? Or is this a cosmos chain that is already connected? Thanks!

**Comment by golnar-m** [comment]
Hi @benjamin852 
We have filled out the connection request form available at this [link](https://docs.google.com/forms/d/18as2Dn7mrcxoic1K4UwnqnViU6QQx3cSuduHBVqYNCQ/viewform?edit_requested=true#response=ACYDBNilAOeWdjJ8cnWODTkG-srrvfmGbwB3gMEw-dUo34OV26h8sA9uNk7_JHSE2U6GO9U) for our chain **[ Soarchain ]**. However, we have not yet received a response regarding the current status.
Could you please update us on the status of our request? Additionally, could you provide a detailed list of the steps we need to take programmatically after the connection of our chain is completed? Thank you.

**Comment by benjamin852** [comment]
Hey @golnar-m I checked internally the team is currently going through a backlog of cosmos chains to be integrated. I've confirmed Soarchain is on our radar (we received your form) and we're attempting to get all these chains hooked up as fast as possible.

**Comment by golnar-m** [comment]
Thank you for update.
