### ISSUE TITLE
sendToken() error from scroll to base: Fail with Custom Error 'TokenDoesNotExist (symbol=AI)

### ISSUE THREAD

**Issue by deandreee** [axelarnetwork/support#121]
I'm trying to send token from scroll to base, the tx gets submitted, but fails with an status error `Fail with Custom Error 'TokenDoesNotExist (symbol=AI)'`

Example [here](https://scrollscan.com/tx/0x95cf49c6b106b7da47341fea64f6cea4e3ebaf12ea90a826e7245bb0fcbc14af)

Here's the params I'm using:
```
const requestOptions: SendTokenParams = {
    fromChain: CHAINS.MAINNET.SCROLL,
    toChain: CHAINS.MAINNET.BASE,
    destinationAddress: wallet.address,
    asset: { symbol: "AI" },
    amountInAtomicUnits: "1",
    options: {
      evmOptions: {
        signer: wallet,
        provider: rpc,
        txOptions: {
          gasLimit: utils.hexlify(100000),
        },
        approveSendForMe: true,
      },
    },
  }
```

The token exists and supports both chains, as you can see on [axelarscan.io](https://axelarscan.io/resources/assets)

Also, I'm getting the same error with other tokens e.g. `AXL`

**Comment by Olanetsoft** [comment]
Hello @deandreee, Thank you for reaching out. Tokens created by Interchain Token Service differ from tokens on the [gateway asset](https://axelarscan.io/resources/assets).

For cross-chain tokens, there are three options available: 

The `sendToken()` to send a token on any Axelar-supported source chain to a recipient on any Axelar-supported destination chain. Transfer assets using a [deposit address](https://docs.axelar.dev/dev/send-tokens/introduction#transfer-assets-using-a-deposit-address) generated with the AxelarJS SDK or you build your own [Interchain Token](https://docs.axelar.dev/dev/send-tokens/introduction#build-an-interchain-token) if your token is not [natively supported](https://docs.axelar.dev/dev/reference/mainnet-contract-addresses#assets). 

So, if you want to send an `AI` token, you can do it directly from the ITS portal on [testnet](https://testnet.interchain.axelar.dev/) or [mainnet](https://interchain.axelar.dev/) or programmatically do the interchain transfer. Could you take a look at this [doc](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/developer-guides/programmatically-create-a-token#transfer-your-token-between-chains)?

Let me know if that helps.
