### ISSUE TITLE
InterchainTokenService: deploy a token manager for a custom interchain token

### ISSUE THREAD

**Issue by rya-sge** [axelarnetwork/support#125]
Goal: Create a custom Interchain Token. The original tokens are deployed on various different chains supported by Axelar.

The tutorial in the [documentation](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/create-token#tutorial) indicates:

> Call [deployTokenManager()](https://github.com/axelarnetwork/interchain-token-service/blob/9edc4318ac1c17231e65886eea72c0f55469d7e5/contracts/InterchainTokenService.sol#L276) to deploy a token manager for your token.The token manager operator will be of type bytes, and the token address will be an address.

Problem:
The function takes 6 arguments (salt, destinationChain, tokenManagerType, params, gasvalue and tokenId)

a) For gasValue, how can I know the value to put inside ?
b) If I have correctly understood, params is made of two types: bytes for the token manager operator  and address for the token address. Is it correct ?

Best!

**Comment by Olanetsoft** [comment]
Hello @rya-sge, thanks for reaching out.

a. For `gasValue`, you can pass in 0 as this is used for multichain calls; in your case, it's not required.
b. Yes, you are correct. See an example [here](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/developer-guides/link-custom-tokens-deployed-across-multiple-chains-into-interchain-tokens#deploy-a-token-manager-on-fantom) with ethers.

If you have any other questions, let me know, and I will be happy to help.
