### ISSUE TITLE
Relayer didn't execute txn automatically.

### ISSUE THREAD

**Issue by adi44** [axelarnetwork/support#126]
i havent got token ethereum-sepolia chain even though txn succeeded

https://testnet.bscscan.com/tx/0xa567214485d3c7fd37f3443290eb9fffd9000073fee91a939a26b9b29462aa29

https://testnet.axelarscan.io/gmp/0x0f7ed9fbc2e68aefdd2078162c51d41f664cb4bd4b4311f4d599da96031896a5-2

It asked me to pay gas manually
I have created token that is function interchainTokenTransfer

**Comment by benjamin852** [comment]
Hey can you clarify what you mean here? I saw this tx did execute correctly, does the transaction get stuck in the pay gas step? I.e. not enough funds were sent? Thanks

**Comment by adi44** [comment]
How do I send funds? I am inheriting the interchain transfer function in my custom tokens contract @benjamin852

**Comment by benjamin852** [comment]
If you inherit from the `InterchainTokenStandard` function then you should be able to send a cross-chain transfer via the `interchainTransfer()` function on the ITS standard as defined [here](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/interchain-token/InterchainTokenStandard.sol#L37)
[Here is an example](https://github.com/axelarnetwork/axelar-examples/blob/main/examples/evm/its-custom-token/index.js#L55) where you can see how to call the `interchainTransfer()` function

**Comment by benjamin852** [comment]
Closing this issue now please re-open if you still are unclear about anything, thanks!
