### ISSUE TITLE
Rename `setTokenId` function and include it in `InterchainTokenStandard`

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/support#128]
The `setTokenId` function in interchain tokens is used to update the interchain token ID to a new value:
https://github.com/axelarnetwork/axelar-examples/blob/8dcaf733bbcde8637ca910e4200c8aa2ebe0ccf5/examples/evm/its-custom-token/CustomToken.sol#L37

https://github.com/axelarnetwork/interchain-token-service/blob/56e9084766280055c664e41e31ca59edac1af62a/contracts/test/TestFeeOnTransferToken.sol#L75

https://github.com/axelarnetwork/interchain-token-service/blob/56e9084766280055c664e41e31ca59edac1af62a/contracts/test/TestInterchainTokenStandard.sol#L83

The `setTokenId` name is too generic, so it should be renamed to `setInterchainTokenId` (or something like `setAxelarTokenId`) so that it's clear that the value of the token ID is for use in Axelar's Interchain Token Service. There could be other contexts in which the term "token ID" is used for the token outside of Axelar, so it's better to be more specific.

Also, I think this function to update the interchain token ID should be specified in the inheritable contracts like `InterchainTokenStandard` and [IInterchainToken](https://github.com/axelarnetwork/interchain-token-service/blob/56e9084766280055c664e41e31ca59edac1af62a/contracts/interfaces/IInterchainToken.sol#L14) as it should exist in all interchain tokens together with [interchainTokenId()](https://github.com/axelarnetwork/interchain-token-service/blob/56e9084766280055c664e41e31ca59edac1af62a/contracts/interfaces/IInterchainToken.sol#L33C5-L33C34) which returns the current value.

The function should of course be only executable by privileged accounts (e.g. admin role) and not made `public` as is done in `CustomToken`, and that can be covered in the implementation of the interface.

**Comment by SKYBITDev3** [comment]
I compared the value of `interchainTokenId` in the example code by adding 
```javascript
    console.log('interchainTokenId from tokenManager: ', tokenId);
    console.log('interchainTokenId from token: ', await source.burnableToken.interchainTokenId());
```
at https://github.com/axelarnetwork/axelar-examples/blob/457f37cd52a270f9d761b54e7660c70adf2a176f/examples/evm/its-mint-burn-from/index.js#L48

The output was
```javascript
interchainTokenId from tokenManager:  0x07e5741b21b38ee71f445a2c7f8d534bb97b493c4461bb5714dcba4e048d5011
interchainTokenId from token:  0x0000000000000000000000000000000000000000000000000000000000000000
```

The example still works because it calls `interchainTransfer` in the `InterchainTokenService` instance on the source blockchain which takes a token ID, so you can pass in the value obtained from the Token Manager:
https://github.com/axelarnetwork /axelar-examples/blob/457f37cd52a270f9d761b54e7660c70adf2a176f/scripts/libs/its-utils.js#L26

However the `interchainTransfer` function in `InterchainTokenStandard` uses the value of `interchainTokenId` in the token itself:
https://github.com/axelarnetwork/interchain-token-service/blob/56e9084766280055c664e41e31ca59edac1af62a/contracts/interchain-token/InterchainTokenStandard.sol#L48

I tested this by replacing `sourceIts.interchainTransfer` with `source.burnableToken.interchainTransfer` and the transaction failed as expected because `interchainTokenId` was zero.

I then added `source.burnableToken.setTokenId(tokenId)` a bit after `const tokenId = await tokenManager.interchainTokenId()` and the transaction completed successfully.

This demonstrates the importance of setting the correct value for `interchainTokenId` in the token, so you should update the example code accordingly, and add `setInterchainTokenId` to the relevant inheritable contracts as suggested above.

**Comment by SKYBITDev3** [comment]
What do you guys think about this?

**Comment by benjamin852** [comment]
Yes thanks for calling this out. The `tokenId` definitely should not be permisionless as it is in this example. The tokenId should be [predictable](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/InterchainTokenService.sol#L213). I am thinking we will just remove this tokenId from the token's storage and only rely on the one that ITS tracks, as this could be confusing to future devs as you pointed out.
