### ISSUE TITLE
Interchain Token Service: Call `transferFrom` if `burnFrom` doesn't exist in the token

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/support#132]
At https://github.com/axelarnetwork/interchain-token-service/blob/56e9084766280055c664e41e31ca59edac1af62a/contracts/TokenHandler.sol#L221 `burnFrom` is called if the Token Manager type is `MINT_BURN_FROM`.

This would fail if the token doesn't have `burnFrom` function, and most tokens don't, because it's not specified in the core ERC20 standard but is an extension, so it must be explicitly added e.g. by importing `ERC20Burnable` from '@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol'.

So there needs to be a fallback to handle the case when `burnFrom` doesn't exist in a token so that such tokens can still be handled by a `MINT_BURN_FROM` Token Manager, which is preferred over `MINT_BURN` because it's much more secure.

`transferFrom` on the other hand is specified in the core ERC20 standard so every ERC20 token has it, so it can be used to burn tokens if `burnFrom` isn't found in the token contract code by transferring them to the zero address.

**Comment by SKYBITDev3** [comment]
Circle's CCIP calls `transferFrom` to itself then`burn`:

https://github.com/smartcontractkit/ccip/blob/e8f60ed319788671dea106b3bb281bf19615adda/contracts/src/v0.8/ccip/test/mocks/MockUSDCTokenMessenger.sol#L30-L31

Though that assumes that there's a public or external `burn` function in the token, doesn't it? Not every ERC20 token out there has `burn` (only an internal `_burn` function that's part of the core ERC20 standard, whereas `burn` and `burnFrom` are extensions).


Also, I've noticed that OpenZeppelin's implementation of ERC20 prevents transfers to the zero address:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e3786e63e6def6f3b71ce7b4b30906123bffe67c/contracts/token/ERC20/ERC20.sol#L166-L171

So what alternatives ways are there to destroy tokens that don't have `burn` or `burnFrom`?

**Comment by benjamin852** [comment]
Yes the issue you pointed out is the big problem. `transferFrom()` will revert eventually if the token is sent to the 0 address ([with OZ's implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e3786e63e6def6f3b71ce7b4b30906123bffe67c/contracts/token/ERC20/ERC20.sol#L170)) that is why we are relying on `burn()` and `burnFrom()` for the different token manager types

**Comment by SKYBITDev3** [comment]
> Yes the issue you pointed out is the big problem. `transferFrom()` will revert eventually if the token is sent to the 0 address ([with OZ's implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e3786e63e6def6f3b71ce7b4b30906123bffe67c/contracts/token/ERC20/ERC20.sol#L170)) that is why we are relying on `burn()` and `burnFrom()` for the different token manager types

But most tokens out there don't have `burnFrom()`, so Circle's method of calling `transferFrom()` to itself then `burn()` is the solution to that... if the token has `burn()`. But how about for already-deployed tokens that don't have `burn()` either? Can there be other ways to destroy them?

Some people advise to transfer tokens to alternative "graveyard" addresses, to which nobody has the private keys, e.g.:
0x0000000000000000000000000000000000000001
0x000000000000000000000000000000000000dEaD

But can there be better solutions?

The aim is to make it possible to use ERC20 tokens that were deployed before Axelar even existed with the Interchain Token Service and `MINT_BURN_FROM` token manager type.

**Comment by SKYBITDev3** [comment]
If you read about 0x000000000000000000000000000000000000dEaD it seems to be commonly understood and used as a burn address.

The protection against the zero address is to handle cases in which there are missing arguments which can end up having a value of 0. Using 0x000000000000000000000000000000000000dEaD means the intention to destroy is explicit, which is better.

So you could handle missing `burnFrom()` cascadingly, e.g.:

First check that `burnFrom()` exists in the token, and call it if so.
If not then check that `burn()` exists, and call `transferFrom()` and `burn()` if so.
If not then call `transferFrom()` to 0x000000000000000000000000000000000000dEaD.

**Comment by benjamin852** [comment]
Really appreciate you digging into this! And putting forward these great questions. `burnFrom()` is an available function from OZ ERC20 standard, it also calls `burn()` which reduces total supply of the token in circulation rather than simply sending it to an unretrievable address where the supply of the token in circulation technically would not be reduced. Your suggestion of having a check if `burnFrom()` exists and using `transferFrom()` to send the token to the dead address (if it does not exist) would work but could pose future challenges for something as critical as burning there should be conformity amongst tokens rather than having a fragmented approach for different tokens and how they go about burning.
