### ISSUE TITLE
Interchain Token Service: Handling plain ERC20 tokens

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/support#134]
I created a basic version of [BurnableToken](https://github.com/axelarnetwork/axelar-examples/blob/main/examples/evm/its-mint-burn-from/BurnableToken.sol) in the examples, with all Axelar code removed, and found that the interchain transfer example still works:
```solidity
import { ERC20 } from '@openzeppelin/contracts/token/ERC20/ERC20.sol';
import { ERC20Burnable } from '@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol'; // adds burnFrom()
import { AccessControl } from '@openzeppelin/contracts/access/AccessControl.sol';

contract BurnableToken2 is ERC20, ERC20Burnable, AccessControl {
    bytes32 public constant MINTER_ROLE = keccak256('MINTER_ROLE');

    constructor(
        string memory name_,
        string memory symbol_,
        uint8 decimalsValue, // unused
        address interchainTokenServiceAddress // unused
    ) ERC20(name_, symbol_) {
        _grantRole(MINTER_ROLE, msg.sender);
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
    }

    function mint(address account, uint256 amount) external onlyRole(MINTER_ROLE) {
        _mint(account, amount);
    }
}
```

I had switched out Axelar's role system for OpenZeppelin's Roles system to simplify it and ensure that all Axelar code is removed. So at https://github.com/axelarnetwork/axelar-examples/blob/075dad5bc037aea2ee0ca271c54ed912695c4a3f/examples/evm/its-mint-burn-from/index.js#L43 I replaced 
```javascript
        await (await chain.burnableToken.addMinter(tokenManagerAddress)).wait();
```
with
```javascript
        await (await chain.burnableToken.grantRole(keccak256(toUtf8Bytes("MINTER_ROLE")), tokenManagerAddress)).wait() // BurnableToken2 uses OpenZeppelin's Roles Access Control
```
which does the same thing.

The main reason it works is because we can call `interchainTransfer` function in the InterchainTokenService contract instead of in the token. the function accepts `interchainTokenId` which can be derived by calling the `interchainTokenId` function in the InterchainTokenService contract (passing it the address of the account that deployed the Token Manager and the salt that was used).

So the minimum requirement for a plain ERC20 token to work with the Interchain Token Service is that it must have a `mint` function to which access by a Token Manager can be granted, so that tokens can arrive at the destination. There's also currently the need for a burn function but I think if you use `transferFrom` instead of `burnFrom` as I've described in https://github.com/axelarnetwork/support/issues/132 then it'll no longer be a requirement.
 
For legacy tokens it appears that "Canonical Tokens" is Axelar's solution to handle them, but can't we just do what I've just described above? Why must Token Managers be "Lock/Release" when Mint/BurnFrom can still work?

**Comment by benjamin852** [comment]
Hi @SKYBITDev3 lock/unlock tokens are designed to be active on a home chain and locked when bridged out. The idea is that tokens deployed on a remote chain are canonical to the tokens that are locked on the token's home chain. So one canonical token on Avalanche for example is backed by a token on ethereum that is locked while that token on avalanche is being used. 
For tokens that do not have a home chain then the better option is to use the mint/burn token manager across all the different chains the token is deployed on. For the tokens using mint/burn then yes the `mint` and `burn` functions are required as these are the functions that will be triggered while bridging. For lock/unlock managers we are only looking for the `safeTransferFrom()` function on the token when it is being locked/unlocked ([see here](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/TokenHandler.sol#L178)). In short, canonical tokens by definition have a home chain which is how lock/unlock managers are designed to be used. If you do not want to have a home chain for your token then you can just use mint/burn managers for all your token deployments. Thanks!
