### ISSUE TITLE
Manual fees payment

### ISSUE THREAD

**Issue by CodeSandwich** [axelarnetwork/support#136]
Hi,
The documentation mentions in https://docs.axelar.dev/dev/gas-service/intro#prepay-gas-on-the-source-chain that:
```
It’s possible for gas fees to be manually paid on the destination chain
```
How can it be done? I haven't found any documentation or examples on this topic.

**Comment by benjamin852** [comment]
Hey! When you import the `AxelarGasService` to your contract you can trigger the function `payNativeGasForContractCall()` this will receive a `msg.value` and that will be sent to Axelar's infrastructure to facilitate the payment on the Axelar blockchain itself and the destination chain once your msg has been sent there. If you overpay `msg.value` then you get refunded the difference. 

Here is an example of how this can be done

1. [Pay the gas for the entire cross-chain tx](https://github.com/axelarnetwork/axelar-examples/blob/main/examples/evm/call-contract/CallContract.sol#L45)
2. [Trigger the cross-chain tx](https://github.com/axelarnetwork/axelar-examples/blob/main/examples/evm/call-contract/CallContract.sol#L52)

**Comment by CodeSandwich** [comment]
The scenario you described and the example you sent are about paying fees on the **source** chain. My question is about paying fees on the **destination** chain, as mentioned in the quote from the documentation. How can the fees be paid on the **destination** chain?

**Comment by benjamin852** [comment]
Right, so when you pay for the transaction on the source chain using the Axelar Gas Service, Axelar's microservices will facilitate that gas payment on the src chain so as long as you use that gas service on the src chain you do not need to worry about making the payment on the destination chain yourself. That is not to say your payment is subsidized but your payment is going to the Axelar relayer on the src chain and in turn the relayer on the destination chain will pay for the tx on the destination chain.
