### ISSUE TITLE
axlUSDC contract needs verified on kavascan's EVM explorer

### ISSUE THREAD

**Issue by Foromador** [axelarnetwork/support#137]
I need to use the "write contract" tab but the contract still needs to be verified https://kavascan.io/token/0xEB466342C4d449BC9f53A865D5Cb90586f405215
If somebody could please verify it then it'd be greatly appreciated

**Comment by Olanetsoft** [comment]
Thanks for flagging. We will take a look and get it verified as soon as possible.

**Comment by Olanetsoft** [comment]
The contract is now verified.
