### ISSUE TITLE
RE: Enquiry of whether Axelar accepts custom blockchains eployed with OP superchain stack.

### ISSUE THREAD

**Issue by chainupk** [axelarnetwork/support#139]
Hi,

I'd like to understand does Axelar accepts integration with  other custom blockchains built with OP Superchain stack? If it does, how long does it take?

**Comment by Olanetsoft** [comment]
Yes, @chainupk. Base, Mode, Mantle, Celo, etc. The list of the supported chains is [here](https://docs.axelar.dev/resources/contract-addresses/mainnet).

Please clarify what you mean by "how long it takes?" If you are referring to the transaction/confirmation, it varies based on different chains. To learn the average time it takes, scroll to the bottom of the statistics page [here](https://axelarscan.io/interchain) on Axelarscan.
