### ISSUE TITLE
Integrating custom EVM into Axelar

### ISSUE THREAD

**Issue by nucash-mining** [axelarnetwork/support#141]
However, it appears that Altcoinchain is not yet supported by Axelar, and I would like to request assistance in adding Altcoinchain to your network. Below are the details for Altcoinchain:

https://altcoinchain.org
Chain Name: Altcoinchain
Chain ID: 2330
RPC URL: http://62.72.177.111:8145/
Block Explorer: http://node-sub.network:4100/
Token Standards: Primarily ERC-20 tokens
Consensus Mechanism: PoW

**Comment by benjamin852** [comment]
Hey! Thanks for your interest here have you taken a look at the Interchain Amplifier docs yet? Going forward we are looking to onboard new chains via the [Amplifier](https://docs.axelar.dev/dev/amplifier/introduction/)

**Comment by nucash-mining** [comment]
Well, I didn't know what part to look in. I'll look at these this week.
Thanks.

**Comment by benjamin852** [comment]
No prob! Closing for now, but feel free to reopen if you have questions on this going forward.

**Comment by nucash-mining** [comment]
@benjamin852 could you add it to Axelar for me? I ended up taking a job offer for some manual labor for the next three months and I won't have much time at a desk while working 7x12s. I'll pay you whatever it's worth.
