### ISSUE TITLE
Cosmos chain with Axelar Amplifier

### ISSUE THREAD

**Issue by arifintahu** [axelarnetwork/support#142]
I have a chain built with the Cosmos SDK without CosmWasm enabled. Is it possible to connect to Axelar Amplifier? If so, how can I integrate Axelar Amplifier with Cosmos chains?

**Comment by benjamin852** [comment]
Hey, Amplifier is designed to facilitate any type of chain (not just EVMs) so yes Cosmos chains should be able to be integrated with Amplifier. Have you checked out our [docs](https://docs.axelar.dev/dev/amplifier/chain-integration/introduction/) yet on how to create a new chain integration?
