### ISSUE TITLE
Absurd fee when using `sendToken` contract call

### ISSUE THREAD

**Issue by andrewliu08** [axelarnetwork/support#145]
Why is the fee so ridiculously high when bridging using the `sendToken` contract call. I bridged 20 axlUSDC from Base to BNB and it took a 11.5 axlUSDC fee.
https://axelarscan.io/transfer/0x0b13cf171cdc3842e12b160643dd9af6f7b07cc8131458169b70fcbc8b1f3f2a

The fees for all routes seem unreasonably high. What is the use case for `sendToken` when the fees are this high?
<img width="727" alt="Screenshot 2024-10-29 at 11 32 37 PM" src="https://github.com/user-attachments/assets/68ff53b7-d7b0-4efd-b986-1198ca7375c1">

The docs on making a cross-chain token transfer also don't mention anything about a fee. Feels like it should mention the fees and link to the fee schedule.
https://docs.axelar.dev/dev/send-tokens/introduction/

**Comment by benjamin852** [comment]
Hi, which service did you use to bridge this asset? By this I mean which frontend were you using, thanks

**Comment by benjamin852** [comment]
In general the `sendToken()` method of sending blockchains is being phased out it is recommended to use the [callContractWithToken()](https://docs.axelar.dev/dev/general-message-passing/gmp-tokens-with-messages/) approach instead. This should have more flexible fee calculation than the more static `sendToken()` approach
