### ISSUE TITLE
Support for Agoric Testnets in AxelarJS-SDK

### ISSUE THREAD

**Issue by rabi-siddique** [axelarnetwork/support#146]
I am exploring the @axelar-network/axelarjs-sdk and noticed that it currently doesn't support Agoric testnets. For our use case, we would like to experiment with Axelar's integration with Agoric. At the moment, our goal is to test the transfer of USDC from Agoric testnets to Ethereum network.

Could you clarify if there are any available environments or workarounds (e.g., sandbox setups, specific test environments) to test Axelar's functionality with Agoric, apart from using the mainnet?

If not, are there plans to support Agoric testnets in the near future? This would greatly help in evaluating Axelar's fit for our use case.

**Comment by benjamin852** [comment]
Hey @rabi-siddique thanks for flagging this. I see the same thing, will confirm if there is a plan to get Agoric supported on testnet as well and update here.

**Comment by rabi-siddique** [comment]
@benjamin852 any news? Just checking in to see if you've had a chance to confirm whether Agoric will be supported on the testnet. Any updates?

**Comment by rabi-siddique** [comment]
I was wondering about the requirements to connect our testnets to Axelar. Would setting up a relayer for IBC messages to link the appropriate Agoric testnet with Axelar be enough?

**Comment by benjamin852** [comment]
Hey the team is currently heads down on the new amplifier integrations  were working on (ie sui, stellar, solana etc.) So I dont think they will be able to setup the testnet integration here until Q1 most likely. Will make sure to followup on this in the new year. If this has not been solved during q1 please feel free to reopen the ticket and I'll get you the latest status of where this is all at. Thanks
