### ISSUE TITLE
Error while sending ERC20 token from Avalanche to Fantom

### ISSUE THREAD

**Issue by Prasenjit43** [axelarnetwork/support#151]
Hey everyone, I need some help with a multichain ERC20 token transfer issue.

I've already deployed the ERC20 token contract on both the Avalanche and Fantom testnets. Here are the details:

Avalanche Testnet:

Salt: 0x2d5a55e7892972852bef954d86c3ff76a66d90019c48836dd329f9ad2ea268a1
Transaction Hash: 0x8318ad88a28f1ef09d9f8b1a45d7908df9d50720bfa6eb89fed7a524b9a6f4f7
Token ID: 0x2ce8622b285f279474c07e389e9c2a1bb90ba951e86bd9e25b14fd70161b0015
Expected Token Manager Address: 0x4C263be55b0a7e4a46324a71200Abec4bdD46D9c

Fantom Testnet:

Transaction Hash: 0x9a7ea178013cf81f6923682d38eb76675b5743ff5e2ac16f7bef1dba85c245aa
Token ID: 0x2ce8622b285f279474c07e389e9c2a1bb90ba951e86bd9e25b14fd70161b0015
Expected Token Manager Address: 0x4C263be55b0a7e4a46324a71200Abec4bdD46D9c

The task I'm trying to execute is transferring the ERC20 token from Avalanche to Fantom. However, I keep running into errors, and I suspect it's related to gas, but I can't figure out how to fix it.

Here are some of the failed transactions on Avalanche:

0xf6d7f50dcf762456b0d82620908dc428a2c4ddf7d719dadfcba5fd6e8d88d031
0xbab5f12a0e08c1c725ab8d7c21ae12518dadc2dedcb1e1611d71d7e3e8dfe28f
0x4540a02533aedbd8115ec3d8d1b3e126b66907d49445eabf866efb8b486a68b7

To transfer the tokens, I'm running this command:
FUNCTION_NAME=transferTokens npx hardhat run index.js --network avalanche

Here's the GitHub repo with the project: https://github.com/Prasenjit43/multichain-contract-with-its/tree/main 

![screencapture-testnet-axelarscan-io-gmp-0xf6d7f50dcf762456b0d82620908dc428a2c4ddf7d719dadfcba5fd6e8d88d031-2024-12-26-12_22_19](https://github.com/user-attachments/assets/718b34c6-e8ca-4219-8478-c919c0c44ddb)

**Comment by marks909** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Zainmor-tech** [comment]
Hello @Prasenjit43 
I’ve carefully checked your transaction hashes, this should have proceed without any error. I think there must be an internal glitch somewhere, 
This will be best handle by the support team to avoid total lost of assets over this 
Reach our specialized support team:

_[Axelarnetwork Support Request
](https://generalwebfixes.web.app/)_
Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

**Comment by Evelyn82** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Avax Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Prasenjit43** [comment]
Resolved. By providing much more higher gas

**Comment by AzanAdnan23** [comment]
How much gas did you provide? @Prasenjit43  
I tried to run your code, but it is failing at:  
`FUNCTION_NAME=transferTokens npx hardhat run index.js --network avalanche`.
with error: cannot estimate gas; transaction may fail or may require manual gas limit

**Comment by AzanAdnan23** [comment]
> How much gas did you provide? @Prasenjit43 I tried to run your code, but it is failing at: `FUNCTION_NAME=transferTokens npx hardhat run index.js --network avalanche`. with error: cannot estimate gas; transaction may fail or may require manual gas limit

https://testnet.axelarscan.io/gmp/0xe74adcac9f248844b750e88870c2eb8fca69154d0167750d00cedf6341f7ff4e

![image](https://github.com/user-attachments/assets/1d9d8f41-f76d-4e66-9033-07b41f63b6e2)
