### ISSUE TITLE
Registered new token on different blockchain using Axelar Interchain Portal

### ISSUE THREAD

**Issue by alkindivv** [axelarnetwork/support#23]
can i register some token by myself even if the token addres owner is not me?

let say some token had same address on different blokchain (Fantom and BSC)
i want to briddge them but its not registered yet, can i registered it by my self beacuse they had the same addres on different blockchain?
example for the token 0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3 (Multi Token)
its deployed on Fantom and BSC scan by someone else, and he's not registered it yet to the axelar services.
can i register and deploy this token at https://beta.interchain.axelar.dev/ so i can bridge the token from BSC to Fantom?

Thanks.

**Comment by Olanetsoft** [comment]
Hello @alkindivv, indeed, you can transfer tokens from BSC (Binance Smart Chain) to Fantom. By pasting the token address you provided into the portal [here](https://beta.interchain.axelar.dev/ethereum/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3), you can view the token information and the chains where the token is currently registered. Once you connect your wallet to the portal, you'll be able to execute token transfers directly from there.

**Comment by alkindivv** [comment]
<img width="633" alt="Screenshot 2024-01-10 at 18 48 30" src="https://github.com/axelarnetwork/support/assets/66145311/330177a6-5184-42ba-ba5a-ccfda0e45a82">

i tried to register the token from BSC to fantom, but why it comes with different contract addres?
0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3 this one is the correct contract addres for both BSC and Fantom, but when i finished registered at Fantom, it comes with this addres 0xdeB27c92E80C5D36Fca441F32Ce2FD161329161b

**Comment by Olanetsoft** [comment]
Closing this. Already in a group and in sync; all questions asked here, along with additional ones, have been resolved.
