### ISSUE TITLE
Nil pointer dereference when calling /cosmos/tx/v1beta1/txs query 

### ISSUE THREAD

**Issue by slnowak** [axelarnetwork/support#24]
Hi guys,
I'm trying to run some basic queries against AXL testnet nodes - for example, this one:
`curl node-url/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&pagination.limit=10`

However, when testing against private AXL testnet node, I've got the following response:
```
{
  "code": 2,
  "message": "runtime error: invalid memory address or nil pointer dereference: panic",
  "details": [
  ]
}
```

Because we couldn't find any obvious error in node logs, I've decided to test this agains few public testnet nodes available here, with the following results:
```
curl "https://lcd-axelar-testnet.imperator.co/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&pagination.limit=10" <- works fine

curl "https://axelartest-lcd.quickapi.com/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&pagination.limit=10" <- fails with the same error (and takes like a 20s to respond)

curl "https://axelar-rest-1.staketab.org/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&pagination.limit=10" <- fails with the same error

curl "https://axelar-testnet-lcd.qubelabs.io/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&pagination.limit=10" <- fails with the same error

curl "https://axelartest-lcd.quantnode.tech/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&pagination.limit=10" <- fails with the same error, also take a lot of time to respond

curl "https://axelar-testnet-api.polkachu.com/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&pagination.limit=10" <- fails with the same error
```

I checked https://lcd-axelar-testnet.imperator.co and https://axelartest-lcd.quickapi.com, they seem to be running the same version. 

Do you guys have any idea what's wrong here? This query works without any issues with other cosmos based chains (ATOM, BLD). 
Any help highly appreciated,

**Comment by benjamin852** [comment]
Hey @slnowak just confirming this is still an issue for you. I am reviewing this as well here.

**Comment by slnowak** [comment]
Yes, this is still an issue. I think this query is somehow inefficient on the backend side.

**Comment by kalidax** [comment]
The query issues seem to be specific to certain AXL testnet nodes rather than a general Axelar network problem, it is working on the lcd-axelar-testnet.imperator.co endpoint. 
The error point to server-side issue on the affected nodes. 
Without access to these servers logs or configurations, we can't definitively diagnose the cause. 
I will ping contact them and we will get back to you when we have more information

**Comment by kalidax** [comment]
@slnowak 
Maybe all the failed nodes were pruned by cosmprund at some point
Or synced from a snapshot pruned by cosmprund
I talked with some operators and there was some compatibility issues between cosmprund and axelard.
