### ISSUE TITLE
What is the best tutorial to get started with Axelar?

### ISSUE THREAD

**Issue by web3superdev** [axelarnetwork/support#25]
I found axelar-local dev, axelar-examples, and some youtube videos, but I'm not sure where to start?

**Comment by benjamin852** [comment]
Welcome to Axelar! Everyone is different but personally I started with the Developer Tutorial videos on youtube to code along with and get a quick working example of an interchain transaction. I recommend [this video](https://www.youtube.com/watch?v=htMVIYzGA34&list=PLh_q0hSKS_y23UECn5GJML0BDhJDDiiiL&index=8) in particular as a good starting point. The rest of the Developer Tutorials is very helpful as well. 

Next, I would recommend going through the [axelar examples repository](https://github.com/axelarnetwork/axelar-examples/tree/main/examples) repo to see working implementations of interchain functionality. Go through the different code examples there the README's are very useful for each example to walk you through how to interact with them.

Beyond this the [docs](https://docs.axelar.dev/) and [Axelar's blog](https://axelar.network/blog) are very helpful resources as well.

**Comment by SKYBITDev3** [comment]
There should be a quickstart guide for the Interchain Token Service, particularly for custom tokens.
