### ISSUE TITLE
Asking for devnet funds

### ISSUE THREAD

**Issue by llPorZall** [axelarnetwork/support#65]
Please send AXL fund to my Axelar address

`axelar15qjfyjrpk94wh9fysyuw0kkqf3x8f6kme84z47`

Thank you 
POR from CONTRIBUTIONDAO team.

**Comment by Olanetsoft** [comment]
Hey @llPorZall, thanks for reaching out. We have just sent the devnet funds for 100 AXL to your address. Please confirm that you have received it.
