### ISSUE TITLE
[Question]: Does Axelar nodes have integration tests for module interactions and cross chain message passing?

### ISSUE THREAD

**Issue by akaladarshi** [axelarnetwork/support#66]
Hi.
I'm exploring the integration tests related to cross-chain message passing, token transfers, and inter-module interactions based on specific message types within the Axelar network. However, I haven't located such tests in the axelarnetwork/axelar-core repository. Could you guide me to where these might be found, if available?

**Comment by benjamin852** [comment]
Hey @akaladarshi. Currently, the integration tests are private the team may consider taking it public in the future but it remains private for now. Thanks
