### ISSUE TITLE
Node SEError - "Failed to run the last command" when running setup-node.sh 

### ISSUE THREAD

**Issue by VincentGOCyber** [axelarnetwork/support#68]
Could you please help me with this issue? Through a VPS (8-core, 24GB RAM, 1200GB SSD) based in Germany, I ran the code and it threw out this error.

I tried both mainnet and testnet, but neither worked.

**[FIRST ATTEMPT]**
**Input:** 
./scripts/setup-node.sh -n mainnet

**Output:**
FAILED to run the last command

script cleanup running
FAILED to run the last command

script cleanup running

**[SECOND ATTEMPT]**
**Input:** 
./scripts/setup-node.sh -n testnet

**Output:**
FAILED to run the last command

script cleanup running
FAILED to run the last command

script cleanup running

**Comment by Olanetsoft** [comment]
Hello @VincentGOCyber, thank you for reporting this issue. Could you please clarify what you were trying to do when you ran setup-node.sh? Additionally, could you point me to the resource or guide you used?

**Comment by VincentGOCyber** [comment]
Hi, I was trying to set up the node (on mainnet) by running the code from this guide: 
https://docs.axelar.dev/node/config-node

Thanks for reply!

**Comment by kalidax** [comment]
Hi @VincentGOCyber 

Could you run in verbose mode ( use -v) please to have more logs ?
please run this before running the command : 
`ls -la` and `pwd`

**Comment by bluebleublack** [comment]
I too am getting this same issue. The script does not work. I would prefer not to show my root folder. But I am in axelarate-community/scripts folder (I just adjusted my command cause I was in the scripts folder)
~/axelarate-community/scripts# ./setup-node.sh -n mainnet
FAILED to run the last command

script cleanup running
FAILED to run the last command

script cleanup running

I will repeatedly show that regardless

Attempted to do a manual install. I think something is wrong with the way the webasm is handled. Didn't work.

**Comment by kalidax** [comment]
Hi @bluebleublack 

Could you also enable debugging before running the script setup-node.sh
`set -x # Enable debugging`

**Comment by kalidax** [comment]
Hi @bluebleublack 

Any update ?

Thanks.
