### ISSUE TITLE
Can I develop my own cross-chain requirements based on axelar-satellite?

### ISSUE THREAD

**Issue by luchenqun** [axelarnetwork/support#81]
I developed an EVM chain based on Op Stack. I now want to cross-chain transfer the TIA in Celestia  chain to the contract on the EVM chain I developed, and also transfer the TIA in the EVM chain contract back to the Celestia chain through cross-chain. Whether my needs can be achieved based on the project https://github.com/axelarnetwork/axelar-satellite.

If my above needs can be realized based on satellite, then in addition to modifying the axelar-satellite project, what other projects do I need to modify (such as whether satellite has a backend system). Thanks!

**Comment by benjamin852** [comment]
Hi, I recommend you adding the token to Squid, as more effort is supporting Squid over Satellite. Here is the instructions to follow to get your token whitelisted on Squid
https://github.com/axelarnetwork/axelar-configs/blob/main/cli/wizard/commands/list-squid-token/README.md

**Comment by luchenqun** [comment]
Thanks you answer!

Actually, our EVM chain is still under development and has not been released yet. I just want to set up a testing environment to verify if it can meet our cross-chain requirements. Once the chain is officially launched, I will implement my cross-chain requirements on the Axelar mainnet. Based on your suggestions, do I need to follow the steps below to verify our cross-chain requirements locally:

1. Set up local nodes for Axelar, our EVM, and Celestia.
2. Deploy an ERC20 contract on the EVM chain.
3. Add the ERC20 contract information to Squid.
4. Modify the Satellite project.

**Comment by benjamin852** [comment]
Hey, sorry I see what you mean now didn't realize your chain was not deployed yet. If you want to just simulate interactions with the axelar stack locally. I would suggest testing with [axelar local dev](https://github.com/axelarnetwork/axelar-local-dev/tree/main), it's a ganache like experience for you to test your contracts.  
See this [doc](https://github.com/axelarnetwork/axelar-local-dev/blob/main/docs/guide_basic.md) for a basic explanation of how to integrate with it.

When do you expect your chain to go live? The Axelar Amplifier will be moving to production soon which will allow teams to onboard their own chains into the Axelar ecosystem until then teams need to be onboarded manually still. 

If you're just testing now I would not worry about satellite/squid integration yet those can be manually integrated by filling out the form I sent earlier by the team.

**Comment by luchenqun** [comment]
Thank you for your response. I will try as per your suggestions.

**Comment by benjamin852** [comment]
Hey just following up here to see if everything is okay. Thanks

**Comment by luchenqun** [comment]
Thank you for your response. I will seek your help again if I have any questions. Once again, thank you for your assistance.
