### ISSUE TITLE
Missing transactions

### ISSUE THREAD

**Issue by shivlim** [axelarnetwork/support#82]
Tried to do interchain token transfer and i get following tx ids but none exist.
====================
Transfer Transaction Hash:  0x0d54777dc91d7a53b44ad00b8554c7bfd320353ed2ef0beaa42ddf67572f3528
Transfer Transaction Hash:  0xee75c26c28584669a198e1a55dff435b91837baced0851a4c4297621a7856523
Transfer Transaction Hash:  0x6156733976df4fbde432556c94cb2ffb606dff6f92930e4ca66f61f270de01a2
Transfer Transaction Hash:  0x9fe1e853adc8013229ede53ae6b144153560f819fc1eb4d6fffd7e9b363dfc42
Transfer Transaction Hash:  0x55bb5f5f62682d3409b9242b7d73117e1866c76f4ec38d02b39f054b5c7c28e2
Transfer Transaction Hash:  0x5c79b2b193b472a5c7727e731d11f7aa62357ea643b6bae2ffeedd12294f2b33
Transfer Transaction Hash:  0xee7b1c87281c107115ea98ceb98bb5f5a87099664b75b0c2150d8effe01dfded
Transfer Transaction Hash:  0x9f6462ccad44b10c794b9bb5ded2e2b2a3b2845757f6774a38c6f34cf5c0e62c
Transfer Transaction Hash:  0x1a59114dfd48106edb1714d5af9d6856b76dae4b3029ed5276af87edb5007bfc
Transfer Transaction Hash:  0x08a3ef69e74bb6b0ccc083fa1a02f18f188241e8815af32731a2421331471d7a
Transfer Transaction Hash:  0x09a727c2a10d9bffcc0cebfbde19dd3db93062c2ac1231459fab056f224cefb6
Transfer Transaction Hash:  0x95d5bd16ca44e828ccf1917c24a234c4cd285a25afc1339b0f59e00c1ac20874
Transfer Transaction Hash:  0x94677a2624a7daca3d4041b5be6869c9c8972bbac7c52d0fd4cbe10d526077a7
Transfer Transaction Hash:  0x771ea485d359190a8a5a63406187becaf22cc63e46e880f2e15e550ce35ac83a
Transfer Transaction Hash:  0xaf8311f2997a314bbeec084f060ad9f7e29d8be6cfcdb21cbba6ea9b69283176
Transfer Transaction Hash:  0xf378fcb4c73d8c7d7d9b2e3179a2b8fe547a1fafe0f24853d6d2fe8fe67f07a4
Transfer Transaction Hash:  0x7f26354a032b45ecbb6131d175a4e9b33ef7ae964c738eb7f3927eb258b3c49e
Transfer Transaction Hash:  0x5cf5a2d661f409ad94e824b80413fa5c284b2b2efe82c21e2e9b7af0c52d3f32
Transfer Transaction Hash:  0xe3214865ffb55dde6ffc5182101118abfaeeb4a7d0ad3c7b7550878283ec040c
Transfer Transaction Hash:  0xde1b9e5dc2696402e0e2e311b5dd4a5883cb9bb966cac081937e7b4ae0eb1cf4
==============

My contract is here https://polygonscan.com/address/0x346675be813678caa0c572fed748713802ae5918

Trying to transfer from polygon to fantom.
This happens after short burst of requests. few go through and than whole thing stops working.

Thanks

**Comment by benjamin852** [comment]
Hey,

Which ones specifically are not showing up? I checked through a few of these and I am able to find all of them on axelarscan.

For example
1) https://axelarscan.io/gmp/0x08a3ef69e74bb6b0ccc083fa1a02f18f188241e8815af32731a2421331471d7a
2) https://axelarscan.io/gmp/0x1a59114dfd48106edb1714d5af9d6856b76dae4b3029ed5276af87edb5007bfc
3) https://axelarscan.io/gmp/0x9f6462ccad44b10c794b9bb5ded2e2b2a3b2845757f6774a38c6f34cf5c0e62c

**Comment by shivlim** [comment]
May be some have appeared when it wasnt there for few days. Here is one from abpove list which is still missing
https://axelarscan.io/gmp/0xde1b9e5dc2696402e0e2e311b5dd4a5883cb9bb966cac081937e7b4ae0eb1cf4

But i see the tx on polygon in mempool
https://polygonscan.com/tx/0xde1b9e5dc2696402e0e2e311b5dd4a5883cb9bb966cac081937e7b4ae0eb1cf4

Shouldnt axelarscan still show the status?

Also i see at times  await interchainToken.interchainTransfer method hangs with no response and i have to kill process.Shouldnt it just timeout/return in any case?

**Comment by benjamin852** [comment]
Hey so this tx is not even appearing on polygonscan if it was not successfully executed on the source chain it won't be picked up by axelarscan, what makes you think it's stuck in the mempool, are you checking on something like blocknative? 

Can you provide more details on this is this if you're trying to call `interchainTransfer()` programmatically? Or via the portal. Please share on how I can attempt to replicate this issue, thanks!

**Comment by benjamin852** [comment]
Hey just checking to see if this is still a blocker for you, thanks
