### ISSUE TITLE
When do interchain transactions get reverted?

### ISSUE THREAD

**Issue by shivlim** [axelarnetwork/support#85]
Iam trying to batch transactions for interchain and they are now getting reverted/refunded.
https://axelarscan.io/gmp/0xc50605f56091c853153fc7eb5bbfed1b8512636d0e9e7ef754fec107b78d1ecf

When does this scenario happen?

Thanks

**Comment by benjamin852** [comment]
Hey, looks like this tx went through. But to answer your question

Reverted would happen if for example there is invalid execution logic in the `execute()` function in a gmp tx on the destination chain

See [here](https://testnet.axelarscan.io/gmp/0xa88e2bfab0b1433096f7d24fc46f965a7c4e8fa98d37d70b346300be634ce055:6) for example
