### ISSUE TITLE
Requesting Support for GMP Contracts Integration on Arbitrum-Sepolia Chain

### ISSUE THREAD

**Issue by MisterDefender** [axelarnetwork/support#87]
Hey everyone,

I've been part of the Axelerian team for the past three months, and I'm reaching out for assistance regarding the integration of GMP contracts (Gateway & GasReceiver) on the `arbitrum-sepolia` chain. Currently, the documentation only covers integration with `arbitrum-goerli`, which has been deprecated.

You can find more details in the documentation here: [Link to doc](https://docs.axelar.dev/resources/contract-addresses/testnet)

Your support in updating this integration would be greatly appreciated. Thank you for your attention to this matter!

Best regards,
Axelerian"

**Comment by Olanetsoft** [comment]
Hello @MisterDefender  @aAnurag7, Arbitrum Sepolia is not yet supported. The team is working on it, and we hope to have it available soon. There isn't a specific ETA yet, but I will get back to you after confirmation and we will also announce once it's live publicly. Thank you for your patience.

**Comment by MisterDefender** [comment]
Sure @Olanetsoft. Thanks for the quick reply. Awaiting for your response. Shall I close this issue??

**Comment by Olanetsoft** [comment]
Hello @MisterDefender,

We just added all the Sepolia L2s to testnet (Arbitrum, Base, Blast, Mantle, Optimism). 

Take a look at the docs for contract details: https://docs.axelar.dev/resources/contract-addresses/testnet

Thank you.

**Comment by MisterDefender** [comment]
Thanks @Olanetsoft for the quick resolution.
