### ISSUE TITLE
Node Startup Failure on Ubuntu 22.04 with Axelar

### ISSUE THREAD

**Issue by karangoraniya** [axelarnetwork/support#88]
**Environment:**
- Operating System: Ubuntu 22.04

**Issue Description:**
I'm experiencing an issue where my Axelar node fails to start on Ubuntu 22.04. Despite following the setup instructions carefully, I encounter the following error message when attempting to run the node:

**Command**
```bash
./scripts/setup-node.sh -n testnet
```
```bash
./scripts/setup-node.sh -n mainnet
```

**Error**
```bash
FAILED to run the last command

script cleanup running
FAILED to run the last command

script cleanup running
```

**Reference**
- [Docs](https://docs.lavanet.xyz/axelar-node/)

**Comment by Olanetsoft** [comment]
Hey, @karangoraniya, thank you for reaching out.

Looking at the error, you didn't add the flag to specify the environment, whether it's mainnet or testnet.

If it is testnet, the command should be 
```
./scripts/setup-node.sh -n testnet
```

For mainnet, it should be
```
./scripts/setup-node.sh -n mainnet
```

Let me know if that helps.

**Comment by karangoraniya** [comment]
I've also tried adding the `separate` flag to the command for both testnet and mainnet, but I encountered the same error.


```
FAILED to run the last command

script cleanup running
FAILED to run the last command

script cleanup running
```

**Comment by karangoraniya** [comment]
> Flagged this internally, I will give you feedback soon. So sorry about that.

@Olanetsoft Any update ?

**Comment by kalidax** [comment]
Hi @karangoraniya 

I see that you are using one of our partners doc to run the node, could you use our doc [https://docs.axelar.dev/node/config-node](url)

Please could you run that command to see from where you are running the script :

`pwd`

Could you also enable debugging before running the script setup-node.sh
`#!/bin/bash
set -x # Enable debugging`

**Comment by kalidax** [comment]
Hi @karangoraniya 
Any update ?

Regards,
Kalid

**Comment by karangoraniya** [comment]
Hey @kalidax 
Sorry for the late reply i was on holiday

`pwd`

```/root/axelarate-community```

`git pull`
```already upto date```

got many things after running debug command

**Comment by kalidax** [comment]
@karangoraniya 

If you could share the output it would be useful

**Comment by karangoraniya** [comment]
@kalidax 

https://gist.github.com/karangoraniya/0ba3e669ce5ac207a00de00cfb314893

**Comment by kalidax** [comment]
Error is here : https://gist.github.com/karangoraniya/0ba3e669ce5ac207a00de00cfb314893#file-gistfile1-txt-L128

Please run 
`export LD_LIBRARY_PATH="/root/.axelar_testnet/lib` 
and run the script again and let me know if it fixed the issue.

**Comment by karangoraniya** [comment]
```
- reset-chain: 0
- axelar-core-version: v0.35.5
- root-directory: /root/.axelar_testnet
- network: testnet
- environment: host
- script_dir: /root/axelarate-community/scripts
- chain-id: axelar-testnet-lisbon-3
- skip-download: false
- arguments:
```

after this prompt i have type **Y**


then got this 
```
All configuration files have been set up

SUCCESS


Run the node via

/root/.axelar_testnet/bin/axelard start [moniker] --home /root/.axelar_testnet >> /root/.axelar_testnet/logs/axelard.log 2>&1 &

More detailed instructions can be found in our docs.

After the node is running,
To follow execution, run 'tail -f /root/.axelar_testnet/logs/axelard.log'
To stop the node, run "pkill -f "axelard start"

CHECK the logs to verify that the process is running as expected

BACKUP but do NOT DELETE the Tendermint consensus key (if running a validator node)
Tendermint consensus key: /root/.axelar_testnet/config/priv_validator_key.json

script cleanup running
```

**Comment by kalidax** [comment]
Looks like it fixed the issue. 
KIndly refer to https://docs.axelar.dev/node/config-node for the next steps.

**Comment by karangoraniya** [comment]
okay 
let me try and get back to you 

thank you
