### ISSUE TITLE
Question on Axelarscan API data

### ISSUE THREAD

**Issue by alexwes** [axelarnetwork/support#89]
hey all qq on the axelarscan api: I am querying the interchainChart endpoint. Was wondering what units the volume and fees are in the response. Also how to best interpret the meaning of these values? Are fees the fees paid on the Axelar Network? or does it also include fees paid on source and destination chains? is there documentation on this? thanks

**Comment by alexwes** [comment]
Some more pointed questions:
1. Are fees denominated in USD?
2. I am querying Axelar onchain data for tx fees: are these a subset of the fees reported in the API? Or are they completely separate? 
3. Is volume in USD?
4. How is a 'user' defined? Is it only sending addresses on source chains? Does it include both sending and receiving address?

**Comment by Olanetsoft** [comment]
Hello @alexwes, thank you for creating this issue.

- The units for `volume` and `fees` are in USD
- `fees` is the estimation of gas fees used to perform cross-chain transfers. It's the sum of deposit services and GMP fees (Base fee + Express fee).  Also, fees are denominated in USD and it includes fees paid on the network. Take a look at this [example transaction](https://axelarscan.io/gmp/4D82F43EF7A92C9ED8FA7ACF32F9E29B4096A5080B1CAC347FA4A6E7DE83D576:50037) on different levels where fees get paid.
- To get only GMP stats, you can use this endpoint: https://docs.axelarscan.io/interchain/GMPChart on the documentation. It's equivalent to https://axelarscan.io/interchain?transfersType=gmp query on Axelarscan.
- `users` is the number of active users (number of unique senders)

I hope that answers your question.

**Comment by alexwes** [comment]
Hey @Olanetsoft, do the `fees` reported in the API include gas refunds?

**Comment by Olanetsoft** [comment]
> * the estimation of gas fees used to perform cross-chain

Apologies for the delay in response here. It doesn't include refunds, just the sum of deposit services and GMP fees (Base fee + Express fee).
